server:
  port: 8080
  servlet:
    context-path: /auto
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/account?useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-Size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,logback
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid
        login-username: admin
        login-password: admin


mybatis:
  mapper-locations: classpath:com/hdd/account/dao/mapper/*.xml
  type-aliases-package: com.hdd.account

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql